version: 2
sources:
  - name: bronze
    database: "{{ env_var('DBT_CATALOG', 'dev') }}"
    schema: bronze
    tables:
      - name: transcripts
        columns:
          - name: symbol
            tests: [not_null]
          - name: year
            tests: [not_null]
          - name: quarter
            tests: [not_null]
          - name: raw_date
            tests: [not_null]
          - name: raw_content
            tests: [not_null]
  - name: silver_notebook_output
    database: "{{ env_var('DBT_CATALOG', 'dev') }}"
    schema: silver
    tables:
      - name: utterances
